FROM python:3.4-onbuild

WORKDIR /usr/src/app

# necessary for the ./bin/wait_for_db script
RUN apt-get update && apt-get install -y postgresql

# docker-ception in order to deploy using docker-machine
# from https://gist.github.com/frgomes/a6f889583860f5b330c06c8b46fa0f42
# compiled from https://docs.docker.com/engine/installation/linux/debian/#/debian-jessie-80-64-bit

RUN apt-get update
RUN apt-get dist-upgrade -y
RUN apt-get install apt-transport-https ca-certificates -y

RUN sh -c "echo deb https://apt.dockerproject.org/repo debian-jessie main > /etc/apt/sources.list.d/docker.list"
RUN apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D

RUN apt-get update
RUN apt-cache policy docker-engine
RUN apt-get install docker-engine -y

RUN pip install docker-compose
RUN curl -L https://github.com/docker/machine/releases/download/v0.12.0/docker-machine-`uname -s`-`uname -m` >/tmp/docker-machine && \
      chmod +x /tmp/docker-machine && \
      cp /tmp/docker-machine /usr/local/bin/docker-machine
