FROM python:3.4-onbuild

WORKDIR /usr/src/app

# necessary for the ./bin/wait_for_db script
RUN apt-get update && apt-get install -y postgresql

RUN apt-get update
RUN apt-get dist-upgrade -y
RUN apt-get install apt-transport-https ca-certificates unzip -y

# install terraform
RUN curl -o ./terraform.zip "https://releases.hashicorp.com/terraform/0.9.6/terraform_0.9.6_linux_amd64.zip"
RUN unzip ./terraform.zip -d /usr/bin
RUN rm ./terraform.zip
