FROM python:3.4-onbuild

WORKDIR /usr/src/app

# necessary for the ./bin/wait_for_db script
RUN apt-get update && apt-get install -y postgresql

RUN apt-get update
RUN apt-get dist-upgrade -y
RUN apt-get install apt-transport-https ca-certificates -y
RUN ssh-keygen -t rsa -q -f ~/.ssh/id_rsa -N ""
