FROM python:3.8

RUN apt-get update && \
  apt-get upgrade -y && \
  apt-get install -y default-mysql-client redis

COPY . /usr/src/app
WORKDIR /usr/src/app
RUN pip install uv
RUN uv pip install --system .

EXPOSE 8000
CMD ["./bin/start_flower"]

