"""empty message

Revision ID: 06fafc461a05
Revises: 7039ec6b9c23
Create Date: 2018-11-05 02:32:33.204917

"""

# revision identifiers, used by Alembic.
revision = '06fafc461a05'
down_revision = '7039ec6b9c23'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('droplets', sa.Column('deletion_date', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('droplets', 'deletion_date')
    # ### end Alembic commands ###
