"""empty message

Revision ID: 5ab1f9b9fbfe
Revises: None
Create Date: 2017-07-09 22:59:39.639894

"""

# revision identifiers, used by Alembic.
revision = '5ab1f9b9fbfe'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('droplets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('droplet_name', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('droplets')
    # ### end Alembic commands ###
