"""empty message

Revision ID: 676b236c57b0
Revises: 7496b85d3049
Create Date: 2017-07-17 00:59:36.986552

"""

# revision identifiers, used by Alembic.
revision = '676b236c57b0'
down_revision = '7496b85d3049'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('droplets', 'droplet_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('droplets', sa.Column('droplet_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
