"""empty message

Revision ID: 7039ec6b9c23
Revises: e3401e85ab93
Create Date: 2018-04-27 21:02:22.262255

"""

# revision identifiers, used by Alembic.
revision = '7039ec6b9c23'
down_revision = 'e3401e85ab93'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('droplets', sa.Column('active', sa.Boolean(), nullable=True))
    op.drop_column('droplets', 'deployed')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('droplets', sa.Column('deployed', sa.BOOLEAN(), nullable=True))
    op.drop_column('droplets', 'active')
    # ### end Alembic commands ###
