"""empty message

Revision ID: 7496b85d3049
Revises: 7796abf5a85a
Create Date: 2017-07-17 00:34:02.406387

"""

# revision identifiers, used by Alembic.
revision = '7496b85d3049'
down_revision = '7796abf5a85a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('droplets', sa.Column('deploy_id', sa.Integer(), nullable=True))
    op.add_column('droplets', sa.Column('repo_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('droplets', 'repo_path')
    op.drop_column('droplets', 'deploy_id')
    # ### end Alembic commands ###
