"""empty message

Revision ID: 7796abf5a85a
Revises: 2ab67e7a2a3b
Create Date: 2017-07-10 00:12:47.395819

"""

# revision identifiers, used by Alembic.
revision = '7796abf5a85a'
down_revision = '2ab67e7a2a3b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # no-op
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
