"""empty message

Revision ID: b39241731c0f
Revises: 2d07e4a2d226
Create Date: 2021-04-25 14:48:47.427848

"""

# revision identifiers, used by Alembic.
revision = 'b39241731c0f'
down_revision = '2d07e4a2d226'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('apps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('confirmed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('repo_slug', sa.String(), nullable=True),
    sa.Column('branch', sa.String(), nullable=True),
    sa.Column('deletion_date', sa.Date(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('warning_email_sent', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('apps')
    # ### end Alembic commands ###
