"""empty message

Revision ID: d8263aebdb52
Revises: 7039ec6b9c23
Create Date: 2018-05-27 19:16:03.650180

"""

# revision identifiers, used by Alembic.
revision = 'd8263aebdb52'
down_revision = '7039ec6b9c23'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('droplets', sa.Column('pr_number', sa.Integer(), nullable=True))
    op.add_column('droplets', sa.Column('to_delete_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('droplets', 'to_delete_at')
    op.drop_column('droplets', 'pr_number')
    # ### end Alembic commands ###
