name: Docker Build CI

on:
  pull_request:
    branches: ["master"]

jobs:
  build-web:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Web Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.web
          push: false
          cache-from: type=gha,scope=web
          cache-to: type=gha,mode=max,scope=web
          load: true

  build-celery:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Celery Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile.celery
          push: false
          cache-from: type=gha,scope=celery
          cache-to: type=gha,mode=max,scope=celery
          load: true
